import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {homedir} from 'node:os';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || `${homedir()}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright`);
const browser=await chromium.launch({headless:true,channel:"msedge"});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.setDefaultTimeout(8000);
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.stack)});page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});page.on('dialog',d=>d.accept());
await page.route('**/src/firebase-config.js',r=>r.fulfill({contentType:'text/javascript',path:fileURLToPath(new URL('./firebase-mock.js',import.meta.url))}));
await page.route('**/src/rip-config.js',r=>r.fulfill({contentType:'text/javascript',body:`export const ripSignIn=async()=>{};export const ripSignOut=async()=>{};export const ripRestoreSession=async()=>({email:'prueba@musicala.co'});export const ripCurrentUser=()=>({email:'prueba@musicala.co'});export const ripFetchEstudiantes=async()=>[{studentId:'ana',nombre:'Ana Activa',claveNombre:'ana activa',area:'Música',instrumento:'Piano',nivel:'activo',etiqueta:'Activo',ultimaClase:'2026-09-01'},{studentId:'bruno',nombre:'Bruno Activo',claveNombre:'bruno activo',area:'Danza',nivel:'activo',etiqueta:'Activo',ultimaClase:'2026-09-01'},{studentId:'camila',nombre:'Camila Inactiva',claveNombre:'camila inactiva',area:'Música',instrumento:'Guitarra',nivel:'inactivo',etiqueta:'Inactivo',ultimaClase:'2026-01-01'}];export const ripNorm=x=>String(x||'').toLowerCase();export const RIP_ALLOWED_EMAILS=[];`}));
try{
 await page.goto(process.env.TEST_URL || 'http://127.0.0.1:4173');
 await page.waitForFunction(()=>window.testStore); await page.locator('#loginBtn').click();await page.locator('#annualBtn').click();
 await page.getByRole('heading',{name:'Sistema Anual de Muestras Artísticas Musicala',exact:true}).waitFor();
 assert.equal(await page.locator('.annual-cycles .annual-card').count(),4);
 await page.locator('[data-annual="edit"]').click();
 await page.locator('[data-path="descripcion"]').fill('Guía institucional verificada en prueba local.');
 await page.locator('[data-annual="saveConfig"]').click();
 await page.waitForFunction(()=>window.testStore.get('configuracion/muestrasProceso')?.revision===1);
 assert.equal(await page.evaluate(()=>window.testStore.get('configuracion/muestrasProceso').descripcion),'Guía institucional verificada en prueba local.');
 assert.ok(await page.evaluate(()=>window.testStore.all().some(([p])=>p.startsWith('configuracion/muestrasProceso/historial/'))));
 await page.locator('[data-annual="dates"]').click();await page.locator('[data-date="1"][data-key="fechaInicio"]').fill('2026-03-17');await page.locator('[data-annual="saveDates"]').click();
 await page.waitForFunction(()=>window.testStore.get('configuracion/muestrasProceso/anios/2026')?.revision===1);
 await page.locator('#annualYear').fill('2027');await page.locator('#annualYear').dispatchEvent('change');
 await page.locator('[data-annual="generate"]').click();
 await page.waitForFunction(()=>window.testStore.all().filter(([p])=>p.startsWith('eventos/')).length===4);
 await page.locator('[data-annual="generate"]').click();
 assert.equal(await page.evaluate(()=>window.testStore.all().filter(([p])=>p.startsWith('eventos/')).length),4);
 await page.locator('[data-annual="generateJornadas"]').click();
 await page.waitForFunction(()=>window.testStore.all().filter(([p])=>p.startsWith('eventos/')).length===40);
 await page.locator('[data-annual="generateJornadas"]').click();
 assert.equal(await page.evaluate(()=>window.testStore.all().filter(([p])=>p.startsWith('eventos/')).length),40);
 await page.locator('#annualYear').fill('2026');await page.locator('#annualYear').dispatchEvent('change');
 await page.waitForFunction(()=>document.querySelector('.annual-cycles').textContent.includes('17 de marzo'));
 await page.reload();await page.locator('#annualBtn').click();
 await page.waitForFunction(()=>document.querySelector('.annual-cycles').textContent.includes('17 de marzo'));
 // Concurrent configuration change must not overwrite the remote revision.
 await page.locator('[data-annual="edit"]').click();await page.locator('[data-path="descripcion"]').fill('Borrador que no debe sobrescribir');
 await page.evaluate(()=>{const c=window.testStore.get('configuracion/muestrasProceso');window.testStore.set('configuracion/muestrasProceso',{...c,descripcion:'Cambio de otro usuario',revision:2});});
 await page.locator('[data-annual="saveConfig"]').click();await page.waitForFunction(()=>document.querySelector('#annualView').textContent.includes('Otra persona cambió'));
 assert.equal(await page.evaluate(()=>window.testStore.get('configuracion/muestrasProceso').descripcion),'Cambio de otro usuario');
 await page.locator('[data-annual="cancelConfig"]').click();
 await page.evaluate(()=>document.querySelectorAll('.toast').forEach(x=>x.remove()));
 await mkdir('tests/artifacts',{recursive:true});await page.screenshot({path:'tests/artifacts/annual-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'tests/artifacts/annual-mobile.png',fullPage:true});
 await page.locator('#annualView').scrollIntoViewIfNeeded();
 await page.evaluate(()=>document.querySelector('#annualView').scrollIntoView());
 await page.screenshot({path:'tests/artifacts/annual-mobile-viewport.png'});
 await page.setViewportSize({width:1440,height:1000});
 // Existing records, capacity and participant editor.
 await page.evaluate(()=>window.testStore.set('eventos/muestra-proceso-2027-1/muestras/old',{estudianteGrupo:'Estudiante antiguo',area:'Música',estado:'Pendiente'}));
 await page.locator('[data-event-id="muestra-proceso-2027-1"]').click();await page.locator('[data-tab="muestras"]').click();
 await page.getByText('Estudiante antiguo',{exact:true}).waitFor();await page.getByText('1 presentación(es) sin familia activa asignada.',{exact:false}).waitFor();
 await page.locator('[data-action="pick-students"]').click();await page.getByText('Ana Activa',{exact:true}).waitFor();await page.locator('[name="modalidadPresentacionId"]').selectOption('piano');assert.equal(await page.locator('.picker-row').count(),1);await page.locator('#modalForm').getByText('Música · Piano',{exact:true}).waitFor();await page.locator('[name="areaArtisticaId"]').selectOption('danza');await page.getByText('Bruno Activo',{exact:true}).waitFor();assert.equal(await page.locator('.picker-row').count(),1);await page.locator('[name="areaArtisticaId"]').selectOption('musica');await page.locator('[name="modalidadPresentacionId"]').selectOption('piano');await page.locator('#pickerCobertura').getByText('1 pendientes',{exact:false}).waitFor();await page.locator('#pickerMarcarPendientes').click();await page.locator('#pickerCobertura').getByText('0 pendientes',{exact:false}).waitFor();assert.equal(await page.locator('[data-pick]:checked').count(),1);await page.locator('[data-close]').click();
 await page.locator('[data-edit-child="muestras:old"]').click();
 await page.locator('[name="areaArtisticaId"]').selectOption('musica');await page.locator('[name="modalidadPresentacionId"]').selectOption('piano');await page.locator('#modalForm button[type="submit"]').click();
 await page.waitForFunction(()=>window.testStore.get('eventos/muestra-proceso-2027-1/muestras/old')?.familiaInstrumentalId==='piano');
 // Cambio contextual: Danza muestra sus propios campos y deja el registro musical intacto.
 await page.locator('[data-action="add-child"]').click();await page.locator('[name="areaArtisticaId"]').selectOption('danza');
 await page.locator('[name="modalidadPresentacionId"]').selectOption('danza-coreografia');
 await page.locator('[name="nombrePresentacion"]').fill('Coreografía de prueba');await page.locator('[name="duracionMin"]').fill('6');
 await page.locator('[name="estudianteGrupo"]').fill('Grupo Danza');await page.locator('#modalForm button[type="submit"]').click();
 await page.waitForFunction(()=>window.testStore.all().some(([p,d])=>p.includes('/muestras/')&&d.areaArtisticaId==='danza'&&d.modalidadPresentacionId==='danza-coreografia'));
 await page.locator('[data-vista="tablero"]').click();await page.getByText('Estudiante antiguo',{exact:true}).waitFor();
 await page.locator('#logoutBtn').click();await page.locator('#loginBtn').waitFor({state:'visible'});
 assert.deepEqual(errors,[]);
 console.log('PASS: login simulado, documento ausente, persistencia y recarga, aislamiento anual, generación repetida, conflicto de edición, antiguo participante, familia, Kanban, móvil sin desborde, cierre de sesión; 0 errores JS.');
}finally{await browser.close();}
